# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    
    # runs-on: ubuntu-latest

    strategy:
      matrix:
       node-version: [14.x, 16.x, 18.x]
      #  node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - run: 
        npm ci
    - run: 
        npm run build --if-present
    #- run: 
     #   npm run start

  # deploy:

  #     # runs-on: ubuntu-latest
  #     runs-on: self-hosted

  #     needs: build

  #     steps:
  #     - name: executing remote
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_KEY}}
  #         port: 22
  #         script: 
  #           # cd apps/react-app/
  #           # git remote add origin https://github.com/firmanputra908/react-app.git
  #           # git pull origin main
  #           # git status
  #           # git install --only=prod
  #           # pm2 run start
  #           npm ci




