# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  stages:
    - build
    - test
    - deploy

  build:
    stage: build
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
      #  node-version: [20.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
    only:
      - test

  test:
    stage: test
    script:
      - echo "Running react test"
      - npm test
    only:
      - test

  deploy:
    stage: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY}}
          port: 22
          script: |
            cd /usr/share/nginx/apps/
            git pull origin main
            npm ci --if-not-present
            git status
            git install --only=prod
            pm2 start npm --name react-app -- run start --if-not-present
            pm2 save
            pm2 restart react-app
    only:
      - test
